# Generated by Django 3.0.6 on 2020-09-12 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=0)),
                ('Username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('midle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transactios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('cash', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('Id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserData')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('Name_product', models.CharField(max_length=60)),
                ('description_product', models.CharField(max_length=500)),
                ('buyers', models.ManyToManyField(to='website.UserData')),
            ],
        ),
    ]
