# Generated by Django 3.0.6 on 2020-09-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactios',
            new_name='transaction',
        ),
    ]
